/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ufps.gui;

import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JTextField;
import ufps.negocio.Imagen;
import ufps.util.ExceptionUFPS;

/**
 *
 * @author FERNEY JARAMILLO
 */
public class Form3 extends javax.swing.JFrame {

  
    private Imagen imagen;
    private JTextField mYText[][];
    
    /**
     * Creates new form Form3
     */
    public Form3(int filas , int columnas) throws ExceptionUFPS {
           initComponents();
        imagen =new Imagen (filas , columnas);
        mYText= new JTextField[filas][columnas];
       
        pintar();
        this.setBounds(0, 0, 900, 600);
        this.setLocationRelativeTo(null);
       
        
     
    }

      private void pintar() {
        this.setBounds(0,0,567,408);  
       
        this.repaint();
        int x = 16;
        int y =20;
        
        for (int i =0 ; i<this.imagen.getFilaColores1().length();i++){
        
            for (int j = 0; j < this.imagen.getFilaColores1().get(i).getPixeles().length(); j++) {
                
                this.mYText[i][j]= new JTextField();
                this.mYText[i][j].setBackground(this.imagen.getFilaColores1().get(i).getPixeles().get(j).getRgb());
                this.mYText[i][j].setBounds(x+(i*10), y+(j*10), 10, 10);
                this.jPanel2.add(this.mYText[i][j]);
                
            }
        
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCrearMarco = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButtonDetectarPatron = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonInvertirGamma = new javax.swing.JButton();
        jButtonFlipHorizontal = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldFilasCortar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldColumnaRecortar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldAltoRecortar = new javax.swing.JTextField();
        jTextFieldAnchoRecortar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonCrearMarco.setBackground(new java.awt.Color(153, 153, 255));
        jButtonCrearMarco.setText("CREAR MARCO");
        jButtonCrearMarco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearMarcoActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 0, 0));
        jButton2.setText("RECORTAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButtonDetectarPatron.setBackground(new java.awt.Color(0, 0, 255));
        jButtonDetectarPatron.setText("DETECTAR PATRON");
        jButtonDetectarPatron.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDetectarPatronActionPerformed(evt);
            }
        });

        jButtonInvertirGamma.setBackground(new java.awt.Color(51, 255, 51));
        jButtonInvertirGamma.setText("INVERTIR GAMMA");

        jButtonFlipHorizontal.setBackground(new java.awt.Color(102, 0, 102));
        jButtonFlipHorizontal.setText("FLIP HORIZONTAL");
        jButtonFlipHorizontal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFlipHorizontalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 328, Short.MAX_VALUE)
        );

        jLabel2.setText("FILA:");

        jLabel3.setText("COLUMNA:");

        jTextFieldColumnaRecortar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldColumnaRecortarActionPerformed(evt);
            }
        });

        jLabel4.setText("ALTO:");

        jTextFieldAnchoRecortar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAnchoRecortarActionPerformed(evt);
            }
        });

        jLabel5.setText("ANCHO:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(46, 46, 46)
                        .addComponent(jButtonCrearMarco, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextFieldFilasCortar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldColumnaRecortar))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jButtonFlipHorizontal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonInvertirGamma, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextFieldAltoRecortar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel5))
                                        .addComponent(jButtonDetectarPatron, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldAnchoRecortar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(51, 52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(228, 228, 228))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jButtonCrearMarco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(29, 29, 29)
                        .addComponent(jButton2)
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldFilasCortar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldColumnaRecortar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldAltoRecortar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldAnchoRecortar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDetectarPatron)
                        .addGap(32, 32, 32)
                        .addComponent(jButtonInvertirGamma)
                        .addGap(28, 28, 28)
                        .addComponent(jButtonFlipHorizontal)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCrearMarcoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearMarcoActionPerformed
        
        this.imagen.crearMarco();
        repintar();
    }//GEN-LAST:event_jButtonCrearMarcoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        
        int filas = Integer.parseInt(jTextFieldFilasCortar.getText());
        int columnas = Integer.parseInt(jTextFieldColumnaRecortar.getText());
        int ancho= Integer.parseInt(jTextFieldAnchoRecortar.getText());
        int alto= Integer.parseInt(jTextFieldAltoRecortar.getText());
       
        this.imagen.cortar(filas, columnas, ancho, alto);
        repintar();
        
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonDetectarPatronActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDetectarPatronActionPerformed
        this.imagen.flipHorizontal();
        repintar();
    }//GEN-LAST:event_jButtonDetectarPatronActionPerformed

    private void jTextFieldColumnaRecortarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldColumnaRecortarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldColumnaRecortarActionPerformed

    private void jTextFieldAnchoRecortarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAnchoRecortarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAnchoRecortarActionPerformed

    private void jButtonFlipHorizontalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFlipHorizontalActionPerformed
        // TODO adthis.imagen.flipHorizontal();
        this.imagen.flipHorizontal();
        repintar();
    }//GEN-LAST:event_jButtonFlipHorizontalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonCrearMarco;
    private javax.swing.JButton jButtonDetectarPatron;
    private javax.swing.JButton jButtonFlipHorizontal;
    private javax.swing.JButton jButtonInvertirGamma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldAltoRecortar;
    private javax.swing.JTextField jTextFieldAnchoRecortar;
    private javax.swing.JTextField jTextFieldColumnaRecortar;
    private javax.swing.JTextField jTextFieldFilasCortar;
    // End of variables declaration//GEN-END:variables

    private void repintar() {
      this.jPanel2.removeAll();
        this.repaint();
       for (int i =0 ; i<this.imagen.getFilaColores1().length();i++){
        
            for (int j = 0; j < this.imagen.getFilaColores1().get(i).getPixeles().length(); j++) {
                
                this.mYText[i][j]= new JTextField();
                this.mYText[i][j].setBackground(this.imagen.getFilaColores1().get(i).getPixeles().get(j).getRgb());
                this.mYText[i][j].setBounds(16+(i*10), 20+(j*10), 10, 10);
                this.jPanel2.add(this.mYText[i][j]);
                
            }
        
       }
       this.repaint();
       
       
    }

  
  
}
